name:               "Ben Batorsky"
description:        "Data Scientist and nice guy"
author:             "bpben"
twitter:            "bpben2"
email:              "benbatorsky@gmail.com"

disqus_shortname:   ""

background:         "/resources/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

gems:
  - jekyll-paginate

logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    ben:
      name:           Ben
      site:           https://www.benbatorsky.com
      avatar:         me.png
      bio:            "I am the type of person who appreciates the telling of a great story.  
      As a data scientist, I am interested in using AI to understand, explore and communicate across borders and boundaries.  
      My focus is on Natural Language Processing and the amazing ways it can help us understand each other and our world.  
      The material on this blog is meant to share my experiences and understandings of complex technologies in a simple way, focused on application."
      email:          benbatorsky@gmail.com
      twitter:        https://twitter.com/bpben2
      github:             http://github.com/bpben
      linkedin:           http://linkedin.com/in/benjamin-batorsky-1b883b27
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: ben
      avatar: me.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
